version: "3.5"

services:
  app:
    build:
      context: front/
      dockerfile: dev.Dockerfile
    container_name: docker-next
    ports:
      - "3000:3000"
    volumes:
      - .:/front
      - .:/front/node_modules
